# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1549e13807cba59c7b2aef2027510d510363f56ceb82b81b36bab64f4c2281967724b4c76218f17e1554a7d3aaa626db5476f9b90fb04868dc5f12d13771c0d7

test:
  secret_key_base: 039917e9898499cd5d94b2714ac6ca719391d681afc9f5ab83707eeb7a2f8279e3677b1489c5875d15d6d542563549130da5f787819edc194220d60cd0524370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
